CREATE DATABASE SplitExpenses;

USE SplitExpenses;

CREATE TABLE `Groups` (
    GID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GName VARCHAR(225) NOT NULL,
    PRIMARY KEY (GID)
)ENGINE=InnoDB AUTO_INCREMENT=1000;

CREATE TABLE Members (
    MID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MName VARCHAR(225) NOT NULL,
    GID INT UNSIGNED NOT NULL,
    Contact VARCHAR(450),
    Owed DOUBLE(25 , 2 ) UNSIGNED NOT NULL DEFAULT 0.00,
    Owe DOUBLE(25 , 2 ) UNSIGNED NOT NULL DEFAULT 0.00,
    PRIMARY KEY (MID),
    FOREIGN KEY (GID)
        REFERENCES `Groups` (GID)
)ENGINE=InnoDB AUTO_INCREMENT=2000;

CREATE TABLE Transactions (
    TID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GID INT UNSIGNED NOT NULL,
    Date DATE NOT NULL,
    PRIMARY KEY (TID),
    FOREIGN KEY (GID)
        REFERENCES `Groups` (GID)
)ENGINE=InnoDB AUTO_INCREMENT=3000;


CREATE TABLE Expenses (
    EID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EName VARCHAR(50) NOT NULL,
    EAmt DOUBLE(25 , 2 ) UNSIGNED NOT NULL,
    MID_paidby INT UNSIGNED NOT NULL,
    TID INT UNSIGNED NOT NULL,
    PRIMARY KEY (EID),
    FOREIGN KEY (MID_paidby)
        REFERENCES Members (MID),
    FOREIGN KEY (TID)
        REFERENCES Transactions (TID)
)ENGINE=InnoDB AUTO_INCREMENT=4000;

 CREATE TABLE Owings (
    OID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    OAmt DOUBLE(25 , 2 ) UNSIGNED NOT NULL,
    MID_owedto INT UNSIGNED NOT NULL,
    MID_owes INT UNSIGNED NOT NULL,
    TID INT UNSIGNED NOT NULL,
    PRIMARY KEY (OID),
    FOREIGN KEY (MID_owedto)
        REFERENCES Members (MID),
    FOREIGN KEY (MID_owes)
        REFERENCES Members (MID),
    FOREIGN KEY (TID)
        REFERENCES Transactions (TID)
)ENGINE=InnoDB AUTO_INCREMENT=5000;


CREATE TABLE Settled (
    SID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SAmt DOUBLE(25 , 2 ) UNSIGNED NOT NULL,
    MID_paidby INT UNSIGNED NOT NULL,
    MID_paidto INT UNSIGNED  NOT NULL,
    TID INT UNSIGNED NOT NULL,
    PRIMARY KEY (SID),
    FOREIGN KEY (TID)
        REFERENCES Transactions (TID),
    FOREIGN KEY (MID_paidby)
        REFERENCES Members (MID),
    FOREIGN KEY (MID_paidto)
        REFERENCES Members (MID)
)ENGINE=InnoDB AUTO_INCREMENT=6000;
